app = "frecuencias-a1-natanael"
primary_region = "gru"

[build.args]
  NEXT_PUBLIC_PASSKEYS_ENABLED = "true"
  NEXT_PUBLIC_GOOGLE_LOGIN_ENABLED = "true"
  NEXT_PUBLIC_TURNSTILE_SITE_KEY = "0x4AAAAAAFMGz7Xtvb2laRhX"

[env]
  PORT = "3000"
  NODE_ENV = "production"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    method = "GET"
    path = "/login"
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
