import { courseSchema } from "./schema";

// Original study material aligned to the learning goals of Frecuencias A1, Unit 1.
// Page references point to the printed pagination, not the PDF page number.
export const frecuenciasA1 = courseSchema.parse({
  id: "frecuencias-a1",
  slug: "frecuencias-a1",
  title: "Frecuencias A1",
  languageCode: "es",
  level: "A1",
  description: "Um caminho guiado para começar a conversar em espanhol com segurança.",
  learningConcepts: [
    { id: "greetings", label: "Cumprimentos" },
    { id: "numbers", label: "Números" },
    { id: "nationality", label: "Nacionalidades" },
    { id: "age-tener", label: "Tener para idade" },
    { id: "personal-questions", label: "Perguntas pessoais" },
    { id: "origin", label: "Origem" },
    { id: "residence", label: "Onde mora" },
    { id: "profession", label: "Profissões" },
  ],
  units: [
    {
      id: "nos-presentamos",
      slug: "nos-presentamos",
      number: 1,
      title: "Nos presentamos",
      active: true,
      description: "Aprenda a cumprimentar, falar de você e conhecer alguém em espanhol.",
      objectives: [
        "Cumprimentar e despedir-se",
        "Apresentar-se e apresentar outra pessoa",
        "Informar nome, origem, idade, profissão e residência",
        "Fazer perguntas pessoais simples",
        "Soletrar e usar números básicos",
      ],
      lessons: [
        {
          id: "l-intro",
          slug: "introduccion",
          order: 1,
          active: true,
          title: "Boas-vindas",
          eyebrow: "Introdução",
          description: "Sua primeira conversa começa aqui.",
          minutes: 4,
          activities: [
            {
              id: "intro-1",
              type: "lesson_content",
              title: "¡Hola!",
              prompt: "Um primeiro encontro",
              skill: "reading",
              minutes: 4,
              body: "Imagine que você chega a uma turma nova em Madri. Antes de falar de viagens ou trabalho, precisa dizer quem é e perguntar quem está à sua frente. Esta unidade constrói exatamente essa conversa, passo a passo.\n\nVocê vai observar modelos curtos, praticar as estruturas, escrever uma apresentação própria e terminar com um pequeno teste. Pode repetir qualquer atividade quando quiser.",
              highlights: ["¡Hola!", "Me llamo…", "¿Y tú?"],
              source: { book: "student", pages: "4–5" },
            },
          ],
        },
        {
          id: "l-objectives",
          slug: "objetivos",
          order: 2,
          active: true,
          title: "O que você vai aprender",
          eyebrow: "Seu roteiro",
          description: "Veja o que conseguirá dizer ao final.",
          minutes: 4,
          activities: [
            {
              id: "objectives-1",
              type: "lesson_content",
              title: "Uma apresentação completa",
              prompt: "Metas da unidade",
              skill: "reading",
              minutes: 4,
              body: "Ao final, você poderá iniciar uma conversa com uma saudação, dizer seu nome, origem, idade, profissão e cidade, além de perguntar essas informações a outra pessoa.\n\nA estrutura da conversa será simples: saudação → nome → origem → idade → trabalho/estudo → cidade → despedida. Não é preciso memorizar tudo de uma vez: cada etapa aparece novamente nos exercícios e nas revisões.",
              highlights: ["¿Cómo te llamas?", "¿De dónde eres?", "¿Dónde vives?"],
              source: { book: "student", pages: "4–5" },
            },
          ],
        },
        {
          id: "l-vocab",
          slug: "vocabulario",
          order: 3,
          active: true,
          title: "Palavras para se apresentar",
          eyebrow: "Vocabulário",
          description: "Saudações, países, números e profissões.",
          minutes: 12,
          activities: [
            {
              id: "vocab-1",
              conceptIds: ["greetings"],
              type: "lesson_content",
              title: "Cumprimentos e dados pessoais",
              prompt: "Palavras em contexto",
              skill: "vocabulary",
              minutes: 4,
              body: "Use hola em qualquer momento informal. Buenos días combina com a manhã; buenas tardes, com a tarde; buenas noches, com a noite. Para encerrar, até logo é hasta luego e até amanhã é hasta mañana.\n\nPara descrever pessoas, repare na concordância: brasileiro é brasileño; brasileira é brasileña. Algumas nacionalidades não mudam com o gênero, como canadiense. Para falar de profissão, a estrutura comum é soy + profissão: Soy profesora.",
              highlights: ["Buenos días", "Hasta luego", "Soy brasileña"],
              source: { book: "student", pages: "6–7, 12–13" },
            },
            {
              id: "vocab-2",
              conceptIds: ["greetings"],
              type: "multiple_choice",
              title: "Uma despedida",
              prompt: "Qual expressão você usaria para dizer ‘até amanhã’?",
              options: ["Buenos días", "Hasta mañana", "¿Qué tal?"],
              answer: "Hasta mañana",
              skill: "vocabulary",
              minutes: 2,
              explanation: "Hasta mañana indica que você espera ver a pessoa no dia seguinte.",
            },
            {
              id: "vocab-3",
              conceptIds: ["nationality"],
              type: "fill_blank",
              title: "Nacionalidade",
              prompt: "María es de Brasil. Ella es ___ .",
              answer: "brasileña",
              accepted: ["brasilena"],
              fullAnswers: ["Ella es brasileña.", "María es de Brasil. Ella es brasileña."],
              skill: "vocabulary",
              minutes: 2,
              explanation: "Com ella, o adjetivo de nacionalidade fica no feminino: brasileña.",
            },
            {
              id: "vocab-4",
              conceptIds: ["numbers"],
              type: "multiple_choice",
              title: "Números",
              prompt: "Como se diz 31 em espanhol?",
              options: ["treinta y uno", "trece y uno", "tres y uno"],
              answer: "treinta y uno",
              skill: "vocabulary",
              minutes: 2,
              explanation: "Depois de treinta, usamos y para ligar a unidade: treinta y uno.",
            },
            {
              id: "vocab-5",
              conceptIds: ["profession"],
              type: "short_answer",
              title: "Uma profissão",
              prompt: "Complete em espanhol: ‘Eu sou professora.’",
              answer: "Soy profesora",
              accepted: ["Yo soy profesora", "Soy profesor", "Yo soy profesor"],
              skill: "vocabulary",
              minutes: 2,
              explanation: "Soy é a forma de ser para yo. O pronome yo pode ser omitido.",
            },
          ],
        },
        {
          id: "l-grammar",
          slug: "gramatica",
          order: 4,
          active: true,
          title: "A gramática da apresentação",
          eyebrow: "Gramática",
          description: "Ser, tener, llamarse, vivir e trabalhar.",
          minutes: 15,
          activities: [
            {
              id: "grammar-1",
              type: "lesson_content",
              title: "Cinco verbos essenciais",
              prompt: "Escolha o verbo pela informação",
              skill: "grammar",
              minutes: 5,
              body: "Nome: Me llamo Ana ou Soy Ana. Origem/nacionalidade e profissão: Soy peruana. Soy médica. Idade: Tengo 29 años. Residência: Vivo en Lima. Trabalho: Trabajo en una clínica.\n\nAo perguntar, use ¿cómo? para o nome, ¿de dónde? para a origem, ¿cuántos años? para a idade e ¿dónde? para a cidade. Em espanhol, a idade usa tener, mesmo que em português digamos ‘tenho’.\n\nFormas úteis: yo soy / tú eres / él es; yo tengo / tú tienes / ella tiene; yo vivo / tú vives / él vive. Em llamarse, o pronome acompanha a pessoa: me llamo, te llamas, se llama.",
              highlights: ["Me llamo Ana", "Tengo 29 años", "Vivo en Lima"],
              source: { book: "student", pages: "8–9" },
            },
            {
              id: "grammar-2",
              conceptIds: ["nationality"],
              type: "multiple_choice",
              title: "Ser ou tener?",
              prompt: "Yo ___ brasileño.",
              options: ["tengo", "soy", "vivo"],
              answer: "soy",
              skill: "grammar",
              minutes: 2,
              explanation: "Para indicar nacionalidade, use ser: soy brasileño.",
            },
            {
              id: "grammar-3",
              conceptIds: ["age-tener"],
              type: "fill_blank",
              title: "Falando a idade",
              prompt: "Ana ___ 26 años.",
              answer: "tiene",
              fullAnswers: ["Ana tiene 26 años."],
              skill: "grammar",
              minutes: 2,
              explanation: "Idade usa tener. Para Ana/ella, a forma é tiene.",
            },
            {
              id: "grammar-4",
              conceptIds: ["residence"],
              type: "ordering",
              title: "Organize a frase",
              prompt: "Monte uma frase para dizer onde você mora.",
              words: ["en", "Vivo", "São Paulo"],
              answer: "Vivo en São Paulo",
              skill: "grammar",
              minutes: 2,
              explanation: "Para residência, use vivir + en + lugar.",
            },
            {
              id: "grammar-5",
              conceptIds: ["personal-questions"],
              type: "short_answer",
              title: "Pergunte o nome",
              prompt: "Como você pergunta informalmente ‘Como você se chama?’",
              answer: "¿Cómo te llamas?",
              accepted: ["Cómo te llamas", "¿Cómo te llamas"],
              skill: "grammar",
              minutes: 2,
              explanation: "Use cómo + te llamas para perguntar o nome a tú.",
            },
            {
              id: "grammar-6",
              conceptIds: ["origin", "personal-questions"],
              type: "multiple_choice",
              title: "Origem",
              prompt: "Qual pergunta combina com ‘Soy de Bogotá’?",
              options: ["¿Cuántos años tienes?", "¿De dónde eres?", "¿Dónde trabajas?"],
              answer: "¿De dónde eres?",
              skill: "grammar",
              minutes: 2,
              explanation: "De dónde pergunta a origem de alguém.",
            },
          ],
        },
        {
          id: "l-listening",
          slug: "escucha",
          order: 5,
          active: true,
          title: "Escute uma apresentação",
          eyebrow: "Listening",
          description: "Uma fala curta para treinar a escuta.",
          minutes: 7,
          activities: [
            {
              id: "listening-1",
              type: "listening",
              title: "Quem está falando?",
              prompt: "Ouça e escolha onde a pessoa mora.",
              transcript:
                "Hola. Me llamo Lucía. Soy argentina y vivo en Santiago. Tengo veintisiete años y trabajo en una escuela.",
              media: { kind: "tts", language: "es-ES" },
              options: ["Buenos Aires", "Santiago", "Madrid"],
              answer: "Santiago",
              skill: "listening",
              minutes: 7,
              explanation:
                "Lucía diz vivo en Santiago. A transcrição aparece depois da sua tentativa.",
              source: { book: "student", pages: "10–13 (objetivos de escuta)" },
            },
          ],
        },
        {
          id: "l-guided",
          slug: "practica-guiada",
          order: 6,
          active: true,
          title: "Prática guiada",
          eyebrow: "Exercícios",
          description: "Transforme modelos em frases suas.",
          minutes: 12,
          activities: [
            {
              id: "guided-1",
              type: "multiple_choice",
              title: "Apresentar alguém",
              prompt: "Como dizer ‘Esta é minha amiga Clara’?",
              options: ["Este es mi amiga Clara", "Esta es mi amiga Clara", "Tengo mi amiga Clara"],
              answer: "Esta es mi amiga Clara",
              skill: "grammar",
              minutes: 2,
              explanation: "Esta acompanha amiga, substantivo feminino.",
            },
            {
              id: "guided-2",
              type: "fill_blank",
              title: "Nome",
              prompt: "¿Cómo te ___? Me llamo Diego.",
              answer: "llamas",
              fullAnswers: ["¿Cómo te llamas?", "¿Cómo te llamas? Me llamo Diego."],
              skill: "grammar",
              minutes: 2,
              explanation: "Para tú, a forma é te llamas.",
            },
            {
              id: "guided-3",
              conceptIds: ["personal-questions"],
              type: "ordering",
              title: "Uma pergunta",
              prompt: "Organize as palavras para perguntar a idade.",
              words: ["tienes", "años", "¿Cuántos"],
              answer: "¿Cuántos años tienes?",
              skill: "grammar",
              minutes: 2,
              explanation: "A pergunta completa é ¿Cuántos años tienes?",
            },
            {
              id: "guided-4",
              conceptIds: ["residence"],
              type: "short_answer",
              title: "Sua cidade",
              prompt: "Escreva ‘Eu moro em Recife’ em espanhol.",
              answer: "Vivo en Recife",
              accepted: ["Yo vivo en Recife"],
              skill: "writing",
              minutes: 2,
              explanation: "Use vivo en + cidade. Yo é opcional.",
            },
            {
              id: "guided-5",
              conceptIds: ["profession"],
              type: "multiple_choice",
              title: "Profissão",
              prompt: "Pablo ___ ingeniero.",
              options: ["tiene", "vive", "es"],
              answer: "es",
              skill: "grammar",
              minutes: 2,
              explanation: "Para profissão, usamos ser: Pablo es ingeniero.",
            },
            {
              id: "guided-6",
              type: "fill_blank",
              title: "Trabalho",
              prompt: "Nosotros ___ en una oficina.",
              answer: "trabajamos",
              fullAnswers: ["Nosotros trabajamos en una oficina."],
              skill: "grammar",
              minutes: 2,
              explanation: "Trabajamos é a forma para nosotros.",
            },
          ],
        },
        {
          id: "l-workbook",
          slug: "practica-complementaria",
          order: 7,
          active: true,
          title: "Prática complementar",
          eyebrow: "Livro de exercícios",
          description: "Mais números, perguntas e concordância.",
          minutes: 10,
          activities: [
            {
              id: "workbook-1",
              type: "lesson_content",
              title: "Uma segunda rodada",
              prompt: "Pratique com autonomia",
              skill: "reading",
              minutes: 2,
              body: "O livro de exercícios retoma números, nacionalidades, profissões e perguntas pessoais. A proposta aqui é praticar os mesmos objetivos com situações novas. Faça os itens sem consultar a explicação; depois observe o feedback.",
              highlights: ["Números", "Nacionalidades", "Perguntas"],
              source: { book: "workbook", pages: "4–9" },
            },
            {
              id: "workbook-2",
              conceptIds: ["numbers"],
              type: "fill_blank",
              title: "O número por extenso",
              prompt: "Escreva 42 por extenso em espanhol: ___",
              answer: "cuarenta y dos",
              skill: "vocabulary",
              minutes: 2,
              explanation: "De 31 a 99, use dezena + y + unidade.",
            },
            {
              id: "workbook-3",
              type: "multiple_choice",
              title: "Concordância",
              prompt: "Elena y Marta son de México. Ellas son ___ .",
              options: ["mexicano", "mexicana", "mexicanas"],
              answer: "mexicanas",
              skill: "grammar",
              minutes: 2,
              explanation: "Ellas pede feminino plural: mexicanas.",
            },
            {
              id: "workbook-4",
              conceptIds: ["origin"],
              type: "ordering",
              title: "Origem de outra pessoa",
              prompt: "Monte a pergunta ‘De onde ela é?’",
              words: ["es", "¿De", "dónde", "ella?"],
              answer: "¿De dónde es ella?",
              skill: "grammar",
              minutes: 2,
              explanation: "A expressão de dónde pergunta a origem; es concorda com ella.",
            },
            {
              id: "workbook-5",
              type: "short_answer",
              title: "Idiomas",
              prompt: "Traduza: ‘Eu falo espanhol e português.’",
              answer: "Hablo español y portugués",
              accepted: ["Yo hablo español y portugués"],
              skill: "vocabulary",
              minutes: 2,
              explanation: "Hablo é a forma de hablar para yo.",
            },
          ],
        },
        {
          id: "l-writing",
          slug: "escritura",
          order: 8,
          active: true,
          title: "Escreva sua apresentação",
          eyebrow: "Writing",
          description: "Escreva um texto curto sobre você.",
          minutes: 10,
          activities: [
            {
              id: "writing-1",
              type: "writing",
              title: "Mi presentación",
              prompt:
                "Apresente-se em espanhol com 5 a 8 frases. Inclua nome, origem, idade, cidade, trabalho ou estudo e um idioma que você fala.",
              skill: "writing",
              minutes: 10,
              minWords: 20,
              guidance: [
                "Comece com Hola, me llamo…",
                "Use tengo para idade e vivo en para cidade.",
                "Termine com uma frase de despedida.",
              ],
              source: { book: "student", pages: "10–13 (produção pessoal)" },
            },
          ],
        },
        {
          id: "l-speaking",
          slug: "conversacion",
          order: 9,
          active: true,
          title: "Fale em voz alta",
          eyebrow: "Speaking",
          description: "Repita uma frase e grave uma apresentação curta.",
          minutes: 9,
          activities: [
            {
              id: "speaking-1",
              type: "speaking",
              title: "¿Cómo te presentas?",
              prompt: "Grave uma resposta à pergunta: ¿Cómo te llamas y de dónde eres?",
              skill: "speaking",
              minutes: 6,
              guidance: [
                "Fale seu nome e sua origem.",
                "Acrescente sua cidade ou profissão se quiser.",
                "Ouça a gravação e digite o que você disse.",
              ],
              source: { book: "student", pages: "4–5, 10–13 (interação oral)" },
            },
            {
              id: "speaking-repeat-1",
              type: "speaking",
              title: "Repita uma frase",
              prompt: "Escute e repita: Hola, me llamo Lucía y vivo en Madrid.",
              skill: "speaking",
              minutes: 3,
              referenceText: "Hola, me llamo Lucía y vivo en Madrid.",
              guidance: [
                "Ouça a frase em espanhol antes de gravar.",
                "Fale a frase inteira com sua voz natural.",
                "Veja os indicadores de pronúncia e tente novamente se quiser.",
              ],
            },
          ],
        },
        {
          id: "l-review",
          slug: "revision",
          order: 10,
          active: true,
          title: "Revisão da unidade",
          eyebrow: "Revisão",
          description: "Recupere as estruturas mais importantes.",
          minutes: 10,
          activities: [
            {
              id: "review-1",
              type: "review",
              title: "Revise: fale sobre você",
              prompt: "Monte uma apresentação curta sobre você usando os modelos abaixo.",
              skill: "grammar",
              minutes: 5,
              body: "Os exemplos são modelos. Troque os dados pelos seus; não precisa escrever nem enviar uma resposta nesta atividade.",
              steps: [
                "Leia cada modelo e toque no áudio para ouvir a pronúncia.",
                "Diga uma frase verdadeira sobre você para cada assunto, em voz alta.",
                "Sem olhar os cartões, diga três frases sobre você e faça uma pergunta. Então avance para a revisão rápida.",
              ],
              cards: [
                {
                  label: "Nome",
                  structure: "Me llamo… / Soy…",
                  examples: ["Me llamo Ana.", "Soy Ana."],
                  practice: "Diga seu nome.",
                },
                {
                  label: "Idade",
                  structure: "Tengo … años.",
                  examples: ["Tengo 25 años."],
                  practice: "Diga sua idade.",
                },
                {
                  label: "Origem",
                  structure: "Soy de…",
                  examples: ["Soy de Brasil.", "Soy brasileña."],
                  practice:
                    "Diga seu país. Para a nacionalidade, você também pode dizer ‘Soy brasileño’ ou ‘Soy brasileña’.",
                },
                {
                  label: "Cidade",
                  structure: "Vivo en…",
                  examples: ["Vivo en Recife."],
                  practice: "Diga onde você mora.",
                },
                {
                  label: "Profissão",
                  structure: "Soy… / Trabajo en…",
                  examples: ["Soy profesor.", "Trabajo en una escuela.", "Soy estudiante."],
                  practice: "Diga sua profissão. Se ainda estuda, use ‘Soy estudiante’.",
                },
                {
                  label: "Perguntas",
                  examples: [
                    "¿Cómo te llamas?",
                    "¿De dónde eres?",
                    "¿Dónde vives?",
                    "¿Cuántos años tienes?",
                  ],
                  practice: "Escolha uma pergunta e fale como se estivesse conversando com alguém.",
                },
              ],
            },
            {
              id: "review-2",
              type: "multiple_choice",
              title: "Revisão rápida",
              prompt: "Qual frase está correta?",
              options: ["Soy 25 años", "Tengo 25 años", "Vivo 25 años"],
              answer: "Tengo 25 años",
              skill: "grammar",
              minutes: 2,
              explanation: "A idade é expressa com tener.",
            },
            {
              id: "review-3",
              conceptIds: ["origin"],
              type: "fill_blank",
              title: "Sua origem",
              prompt: "Soy ___ Colombia.",
              answer: "de",
              fullAnswers: ["Soy de Colombia."],
              skill: "grammar",
              minutes: 1,
              explanation: "Para indicar lugar de origem: ser de + lugar.",
            },
            {
              id: "review-4",
              conceptIds: ["personal-questions"],
              type: "short_answer",
              title: "Pergunta útil",
              prompt: "Como perguntar ‘Onde você mora?’",
              answer: "¿Dónde vives?",
              accepted: ["Dónde vives", "¿Dónde vives"],
              skill: "grammar",
              minutes: 2,
              explanation: "Dónde pergunta um lugar; vives é a forma para tú.",
            },
          ],
        },
        {
          id: "l-assessment",
          slug: "evaluacion-final",
          order: 11,
          active: true,
          title: "Avaliação final",
          eyebrow: "Teste",
          description: "Confira o que já consegue fazer.",
          minutes: 15,
          activities: [
            {
              id: "assessment-intro",
              type: "quiz",
              title: "Antes de começar",
              prompt:
                "Responda sem consultar as lições. Seu resultado mostrará pontos fortes e o que revisar.",
              body: "O teste combina vocabulário, gramática, leitura e uma produção escrita breve. Você pode repetir depois de revisar seus pontos fracos.",
              skill: "reading",
              minutes: 1,
            },
            {
              id: "assessment-1",
              conceptIds: ["greetings"],
              type: "multiple_choice",
              title: "1 · Saudação",
              prompt: "Qual expressão é uma saudação?",
              options: ["Hasta luego", "Buenos días", "Adiós"],
              answer: "Buenos días",
              skill: "vocabulary",
              minutes: 2,
              explanation: "Buenos días é uma saudação usada pela manhã.",
            },
            {
              id: "assessment-2",
              conceptIds: ["age-tener"],
              type: "fill_blank",
              title: "2 · Idade",
              prompt: "Yo ___ 30 años.",
              answer: "tengo",
              fullAnswers: ["Yo tengo 30 años."],
              skill: "grammar",
              minutes: 2,
              explanation: "Tener expressa idade; para yo, a forma é tengo.",
            },
            {
              id: "assessment-3",
              conceptIds: ["nationality"],
              type: "multiple_choice",
              title: "3 · Nacionalidade",
              prompt: "Camila es de Argentina. Ella es ___ .",
              options: ["argentino", "argentina", "argentinos"],
              answer: "argentina",
              skill: "grammar",
              minutes: 2,
              explanation: "Ella pede adjetivo feminino singular.",
            },
            {
              id: "assessment-4",
              type: "short_answer",
              title: "4 · Nome",
              prompt: "Escreva em espanhol: ‘Meu nome é Luis.’",
              answer: "Me llamo Luis",
              accepted: ["Soy Luis", "Yo me llamo Luis"],
              skill: "writing",
              minutes: 2,
              explanation: "Me llamo Luis e Soy Luis apresentam seu nome.",
            },
            {
              id: "assessment-5",
              conceptIds: ["residence"],
              type: "multiple_choice",
              title: "5 · Leitura",
              prompt: "Leia: ‘Soy médica y vivo en Quito.’ O que sabemos?",
              options: ["Ela trabalha em Quito", "Ela mora em Quito", "Ela nasceu em Quito"],
              answer: "Ela mora em Quito",
              skill: "reading",
              minutes: 2,
              explanation: "Vivo en indica residência, não origem ou local de trabalho.",
            },
            {
              id: "assessment-6",
              conceptIds: ["origin", "personal-questions"],
              type: "ordering",
              title: "6 · Pergunta",
              prompt: "Monte uma pergunta sobre origem.",
              words: ["eres?", "dónde", "¿De"],
              answer: "¿De dónde eres?",
              skill: "grammar",
              minutes: 2,
              explanation: "A pergunta sobre origem é ¿De dónde eres?",
            },
            {
              id: "assessment-writing",
              type: "writing",
              title: "7 · Produção",
              prompt:
                "Escreva três frases em espanhol para apresentar uma pessoa fictícia. Inclua nome, origem e cidade.",
              skill: "writing",
              minutes: 4,
              minWords: 12,
              guidance: [
                "Use se llama para o nome.",
                "Use es de para a origem.",
                "Use vive en para a cidade.",
              ],
            },
          ],
        },
      ],
    },
  ],
});

export const vocabularySeed = [
  {
    id: "hola",
    spanish: "hola",
    translation: "olá",
    example: "Hola, ¿qué tal?",
    lessonId: "l-vocab",
  },
  {
    id: "buenos-dias",
    spanish: "buenos días",
    translation: "bom dia",
    example: "Buenos días, Marta.",
    lessonId: "l-vocab",
  },
  {
    id: "buenas-tardes",
    spanish: "buenas tardes",
    translation: "boa tarde",
    example: "Buenas tardes, señor Ruiz.",
    lessonId: "l-vocab",
  },
  {
    id: "hasta-luego",
    spanish: "hasta luego",
    translation: "até logo",
    example: "Nos vemos. ¡Hasta luego!",
    lessonId: "l-vocab",
  },
  {
    id: "hasta-manana",
    spanish: "hasta mañana",
    translation: "até amanhã",
    example: "Adiós, hasta mañana.",
    lessonId: "l-vocab",
  },
  {
    id: "llamarse",
    spanish: "llamarse",
    translation: "chamar-se",
    example: "Me llamo Elena.",
    lessonId: "l-grammar",
  },
  {
    id: "tener",
    spanish: "tener",
    translation: "ter",
    example: "Tengo 27 años.",
    lessonId: "l-grammar",
  },
  {
    id: "vivir",
    spanish: "vivir",
    translation: "morar; viver",
    example: "Vivo en Lima.",
    lessonId: "l-grammar",
  },
  {
    id: "trabajar",
    spanish: "trabajar",
    translation: "trabalhar",
    example: "Trabajo en una escuela.",
    lessonId: "l-grammar",
  },
  {
    id: "brasileno",
    spanish: "brasileño / brasileña",
    translation: "brasileiro / brasileira",
    example: "Ella es brasileña.",
    lessonId: "l-vocab",
  },
  {
    id: "argentino",
    spanish: "argentino / argentina",
    translation: "argentino / argentina",
    example: "Él es argentino.",
    lessonId: "l-vocab",
  },
  {
    id: "profesor",
    spanish: "profesor / profesora",
    translation: "professor / professora",
    example: "Soy profesora de español.",
    lessonId: "l-vocab",
  },
  {
    id: "medico",
    spanish: "médico / médica",
    translation: "médico / médica",
    example: "Mi hermana es médica.",
    lessonId: "l-vocab",
  },
  {
    id: "treinta",
    spanish: "treinta",
    translation: "trinta",
    example: "Tengo treinta años.",
    lessonId: "l-vocab",
  },
  {
    id: "donde",
    spanish: "¿dónde?",
    translation: "onde?",
    example: "¿Dónde vives?",
    lessonId: "l-grammar",
  },
  {
    id: "de-donde",
    spanish: "¿de dónde?",
    translation: "de onde?",
    example: "¿De dónde eres?",
    lessonId: "l-grammar",
  },
  {
    id: "cuantos",
    spanish: "¿cuántos?",
    translation: "quantos?",
    example: "¿Cuántos años tienes?",
    lessonId: "l-grammar",
  },
  {
    id: "hablar",
    spanish: "hablar",
    translation: "falar",
    example: "Hablo español y portugués.",
    lessonId: "l-workbook",
  },
] as const;
